### ISSUE TITLE
Codeclimate integration

### ISSUE THREAD

**Issue by jhmartin** [AlexRudd/key-manager#10]
Consider using CodeClimate and its gofmt/golint/govet engines to watch this repo for style and potential bugs, particularly since this tool is security-related.

**Comment by alexrudd** [comment]
Integrated. The only issues so far are formatting related (README.md and main.go)

I've fixed the formatting of the Go code, will look at what it suggests for the README when I get a chance.

Thanks!

**Comment by alexrudd** [comment]
Fixed what README issues I could.
