### ISSUE TITLE
Time sync issue

### ISSUE THREAD

**Issue by jhmartin** [AlexRudd/key-manager#13]
I had a host that's time was 300.7s off from 'correct'.  The 'aws' command was able to talk to the API from the same node, but key-manager resulted in no output.

Debug output resulted in:
```
AuthFailure: AWS was not able to validate the provided access credentials
	status code: 401, request id: SNIP
```

Perhaps failure-message can be emitted in commented / sshd-safe form:

```
# AuthFailure: AWS was not able to validate the provided access credentials
#	status code: 401, request id: SNIP
```

Also, if the required s3 options are not provided then emit the usage.

**Comment by alexrudd** [comment]
Good idea, will implement as soon as I get a chance.

Thanks!

**Comment by alexrudd** [comment]
```
docker run alexrudd/key-manager:2.1
# RequestError: send request failed
# caused by: Get http://169.254.169.254/latest/meta-data/instance-id: dial tcp 169.254.169.254:80: getsockopt: no route to host
```
