### ISSUE TITLE
OSX build

### ISSUE THREAD

**Issue by jhmartin** [AlexRudd/key-manager#5]
On OSX 10.11.3, the awk in 'make build' pulls the incorrect column:

`drwxr-xr-x  3 jhmartin  xxx\Domain Users   102 Sep 15 08:52 _src`
$9 is 08:52.  The build script should reference $10.

Wget is not available by default as well, though curl is.

**Comment by alexrudd** [comment]
Hey, Just took a look at this. I'm running OSX 10.12 and don't experience this same issue.

Then again I don't have the "xxx\Domain" column in my `ls` output:
`drwxr-xr-x   3 alex  staff     102 23 Oct 23:00 _src`

Have changed the expressions to `awk '{ print $NF }'` to pull the final column regardless.

On a related note: this was the fist time I've tried building the project on my macbook and I also hit a problem with `wget` not being a standard comand line tool. Have switched to using `curl`
