### ISSUE TITLE
SELinux labels on docker volumes

### ISSUE THREAD

**Issue by jhmartin** [AlexRudd/key-manager#7]
When performing a `make build` on a host that has SELinux set to enforcing, the volumes mounted with -v need to have a :z added to their mount statement so they are labeled properly.

**Comment by alexrudd** [comment]
I added the `:z` option to the following lines:

```
	-v `pwd`:/go/src/${gitrepo}/${name}:z \
	-v `pwd`/_pkg:/go/pkg:z \
	-v `pwd`/_bin:/go/bin:z \
	-v `pwd`/_src:/go/src:z \
```

And it still builds successfully for me, if you've confirmed that this definitely fixes your problem regarding SELinux, then I'll be happy to commit it.

Though if you could, please provides some details about the OS, docker version, and steps to reproduce, that lead you to discover and diagnose this problem.

Thanks,
Alex

**Comment by jhmartin** [comment]
This was on CoreOS w/SELinux set to enforcing, Docker 1.12.3. I don't have it in front of me but following the normal build procedure triggered it.

**Comment by alexrudd** [comment]
Thanks, have tested this too and made some changes to the Makefile.
