### ISSUE TITLE
Newline handling with multiple groups

### ISSUE THREAD

**Issue by jhmartin** [AlexRudd/key-manager#8]
I have two groups with access to a given node. I had to add a blank line to the end of the 'first' groups authorized_keys file in order for the 2nd file to work (only had one key). I suspect something about the newline is confusing SSHD such that it skips that key.

It would probably be safer to ensure that a full newline is added after the end of each file before it is emitted to SSHD.

For debugging purposes I think it'd be even better to have each 'file' block be prepended by
BLANKLINE
\# GROUPNAME starts here
(contents)

This would cover both the debugging and the newlines.

**Comment by alexrudd** [comment]
Hey, I've pushed a version to docker hub with the changes you suggested. Could you check this fixes your problem? If so I'll commit and release.

image: `alexrudd/key-manager:2.0`

**Comment by jhmartin** [comment]
Fixed! Easier to read too.
